//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FaultyComponents
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewFujiScrapSQliteLine1
    {
        public Nullable<System.DateTime> InsertionTime { get; set; }
        public string Line { get; set; }
        public int IDSQlite { get; set; }
        public System.DateTime DateTime { get; set; }
        public Nullable<byte> Module { get; set; }
        public Nullable<int> PCBCount { get; set; }
        public string Recipe { get; set; }
        public Nullable<short> Name1 { get; set; }
        public Nullable<short> Name2 { get; set; }
        public Nullable<short> Slot { get; set; }
        public Nullable<short> Name3 { get; set; }
        public Nullable<double> PickUp { get; set; }
        public Nullable<double> TotalError { get; set; }
        public Nullable<double> Error { get; set; }
        public Nullable<double> Reject { get; set; }
        public Nullable<double> Dislodged { get; set; }
        public Nullable<double> NoPickUp { get; set; }
        public Nullable<double> Usage { get; set; }
        public Nullable<byte> Name4 { get; set; }
        public string Part { get; set; }
        public Nullable<byte> Name5 { get; set; }
        public string Feeder { get; set; }
        public Nullable<byte> Module1 { get; set; }
    }
}
